import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Clipboard, Calendar, Shield } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Getting Started at Tasel Health: New Patient Guide | Oklahoma City', description: 'Your complete guide to starting mental health treatment at Tasel Health: first visit, intake process, insurance, and creating your care plan.', keywords: ['Tasel Health new patient', 'mental health intake', 'first psychiatry appointment', 'getting started mental health treatment Oklahoma City']}

export default function GettingStartedPage() {
  const keyTakeaways = ["Free consultation available to discuss your needs and determine best treatment approach", "Comprehensive intake evaluates history, symptoms, goals, and treatment preferences", "We accept most major insurance plans; verify coverage before first visit", "Treatment options include TMS, medication management, therapy, or comprehensive care", "Telehealth available for Oklahoma and Texas residents"]
  const faqs = [{question: "How do I schedule my first appointment?", answer: "Call us at (405) 934-1681 (Oklahoma City) or (210) 202-2341 (San Antonio), or use our online contact form. We'll schedule a free consultation to discuss your needs and determine which services are right for you."}, {question: "What should I bring to my first visit?", answer: "Valid ID, insurance card, list of current medications (including dosages), any prior psychiatric records or evaluations, list of previous treatments tried, and questions you want to ask."}, {question: "How long is the first appointment?", answer: "Initial consultations are 10-15 minutes (free). Comprehensive intake appointments are 45-60 minutes. We take time to understand your situation thoroughly."}, {question: "Do you accept my insurance?", answer: "We accept most major commercial and government insurance plans including UnitedHealthcare, Blue Cross Blue Shield, Aetna, Cigna, Medicare, Medicaid, and more. Contact us to verify your specific plan."}, {question: "What if I don't have insurance?", answer: "We offer transparent self-pay rates and payment plans. Contact our billing team at (405) 934-1681 (Oklahoma City) or (210) 202-2341 (San Antonio) to discuss options."}, {question: "Can I do telehealth or do I need to come in person?", answer: "We offer secure telehealth for residents of Oklahoma and Texas. Some services (TMS) require in-person visits. We'll discuss which format works best for your treatment needs."}, {question: "How quickly can I be seen?", answer: "We often have same-week availability for new patients. Urgent concerns may be seen even sooner. Contact us to discuss your timeline."}, {question: "What happens after the intake?", answer: "Your provider will review findings with you, discuss diagnosis if applicable, explain treatment options, and collaborate with you to create a personalized treatment plan. You'll leave with clear next steps."}, {question: "Can you coordinate with my other doctors?", answer: "Yes! With your written consent, we coordinate care with your primary care provider, therapist, or other specialists to ensure comprehensive, integrated treatment."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Getting Started at Tasel Health: What to Expect" summary="Complete guide to your first visit: what to bring, intake process, insurance, creating your treatment plan, and next steps." estimatedReadTime={11} lastReviewed="January 14, 2025" author="Tasel Health Medical Team" clinicalReviewer="Clinical Operations Director" tags={['Getting Started', 'New Patients', 'Intake', 'Insurance']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Step 1: Free Consultation</h2><p className="mb-4">Your journey begins with a brief, no-cost consultation where we discuss your needs, explain our services, and determine if we're a good fit.</p></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Step 2: Comprehensive Intake</h2><p className="mb-4">Your intake appointment includes:</p><ul className="list-disc pl-6 mb-4 space-y-2"><li>Complete mental health history</li><li>Current symptoms and functioning</li><li>Treatment goals and preferences</li><li>Medical history and current medications</li><li>Family history and social supports</li><li>Previous treatment experiences</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Step 3: Treatment Planning</h2><p className="mb-4">Together, we'll create a personalized plan that may include:</p><ul className="list-disc pl-6 mb-4 space-y-1"><li>TMS therapy for treatment-resistant depression</li><li>Medication management</li><li>Individual, couples, or family therapy</li><li>Comprehensive care combining multiple approaches</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Information</h2><ul className="space-y-2"><li><strong>Phone:</strong> <a href="tel:+14059341681" className="text-purple-600 hover:underline">(405) 934-1681</a> (Oklahoma City) | <a href="tel:+12102022341" className="text-purple-600 hover:underline">(210) 202-2341</a> (San Antonio)</li><li><strong>Email:</strong> <a href="mailto:info@taselhealth.com" className="text-purple-600 hover:underline">info@taselhealth.com</a></li><li><strong>Address:</strong> Oklahoma City, OK | San Antonio, TX</li><li><strong>States Served:</strong> Oklahoma, Texas (telehealth)</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/comprehensive-treatment-options-guide" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Treatment Options Guide</h3><p className="text-sm text-gray-600">Compare all treatments</p></Card></Link><Link href="/insurance" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Insurance & Coverage</h3><p className="text-sm text-gray-600">Accepted plans</p></Card></Link><Link href="/contact" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Contact Us</h3><p className="text-sm text-gray-600">Schedule consultation</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
