import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Shield, Heart } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Trauma Therapy: EMDR, CPT & Evidence-Based PTSD Treatment', description: 'Learn about trauma-focused therapy approaches: EMDR, prolonged exposure, CPT. How trauma therapy works and what makes it safe.', keywords: ['trauma therapy', 'PTSD treatment', 'EMDR therapy', 'trauma counseling', 'processing trauma']}

export default function TraumaTherapyPage() {
  const keyTakeaways = ["Trauma therapy helps process difficult experiences in a safe, controlled environment", "Multiple evidence-based approaches: EMDR, prolonged exposure, CPT", "Safety and pacing are prioritized—you control the process", "Therapy addresses both trauma memories and present-day symptoms", "Many people with PTSD benefit from combining therapy with medication"]
  const faqs = [{question: "What is trauma therapy?", answer: "Trauma-focused therapy helps you process traumatic experiences and reduce PTSD symptoms. Unlike regular talk therapy, trauma therapy uses specific techniques to help your brain integrate traumatic memories so they're less distressing."}, {question: "What is EMDR?", answer: "Eye Movement Desensitization and Reprocessing uses bilateral stimulation (eye movements, tapping, or sounds) while you recall traumatic memories. This helps your brain reprocess the memory in a less distressing way. EMDR is well-researched and effective for PTSD."}, {question: "Will I have to talk about every detail of my trauma?", answer: "Not necessarily. EMDR can be effective without detailed verbal description. Other approaches (prolonged exposure, CPT) involve more narrative, but you and your therapist decide the pace. You're always in control."}, {question: "Is trauma therapy safe?", answer: "Yes, when done by a trained therapist. We establish safety, teach coping skills first, and pace trauma work carefully. You won't be pushed beyond what you can handle. If it ever feels too intense, we slow down."}, {question: "Can trauma therapy make PTSD worse?", answer: "Temporary increases in distress can happen when processing trauma—this is normal and usually brief. Your therapist monitors this carefully. Overall, research shows trauma-focused therapy significantly reduces PTSD symptoms and improves quality of life."}, {question: "Do I need medication for PTSD?", answer: "Not everyone needs medication, but many people with PTSD benefit from combining SSRIs (sertraline, paroxetine) or SNRIs (venlafaxine) with trauma therapy. Medication can help reduce baseline anxiety enough to engage with therapy."}, {question: "How long does trauma therapy take?", answer: "Varies by approach and trauma complexity. EMDR might be 8-12 sessions for single-event trauma. Prolonged exposure is typically 8-15 sessions. Complex trauma may require longer treatment. Your therapist will discuss realistic timelines."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Trauma Therapy: Evidence-Based Approaches & Safety" summary="Understand trauma-focused therapy: EMDR, prolonged exposure, CPT, and how therapists create safety while processing difficult experiences." estimatedReadTime={12} lastReviewed="June 22, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Therapy', 'Trauma', 'PTSD', 'EMDR', 'Safety']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Evidence-Based Trauma Approaches</h2><div className="space-y-4"><Card className="p-6 border-l-4 border-purple-500"><h3 className="text-xl font-bold text-gray-900 mb-2">EMDR (Eye Movement Desensitization & Reprocessing)</h3><p className="text-gray-700">Uses bilateral stimulation to help brain reprocess traumatic memories. Highly effective for PTSD with strong research support.</p></Card><Card className="p-6 border-l-4 border-blue-500"><h3 className="text-xl font-bold text-gray-900 mb-2">Prolonged Exposure (PE)</h3><p className="text-gray-700">Gradual, repeated confrontation with trauma memories and reminders in safe environment. Helps reduce avoidance and fear.</p></Card><Card className="p-6 border-l-4 border-teal-500"><h3 className="text-xl font-bold text-gray-900 mb-2">Cognitive Processing Therapy (CPT)</h3><p className="text-gray-700">Helps you challenge and modify unhelpful beliefs about trauma. Addresses stuck points in how you think about what happened.</p></Card></div></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Shapiro F. (2018). "Eye movement desensitization and reprocessing: Basic principles, protocols, and procedures." (3rd ed.) Guilford Press.</li><li>2. VA/DOD Clinical Practice Guideline for PTSD (2017). Department of Veterans Affairs.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/how-therapy-works" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">How Therapy Works</h3><p className="text-sm text-gray-600">Therapy overview</p></Card></Link><Link href="/knowledge-hub/dbt-skills-emotion-regulation" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">DBT Skills</h3><p className="text-sm text-gray-600">Emotion regulation</p></Card></Link><Link href="/knowledge-hub/5-minute-calm-breathing-grounding" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Grounding Techniques</h3><p className="text-sm text-gray-600">Distress management</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
