import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Brain, Pill, MessageSquare, Sparkles } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Mental Health Treatment Options: TMS, Medication & Therapy Compared', description: 'Compare mental health treatment options: TMS therapy, psychiatric medications, and counseling. Understand benefits, timelines, and comprehensive care.', keywords: ['mental health treatment options', 'TMS vs medication vs therapy', 'depression treatment comparison', 'comprehensive mental health care']}

export default function ComprehensiveTreatmentGuidePage() {
  const keyTakeaways = ["Treatment approaches include TMS, medication, therapy, and Spravato® & Ketamine—each with strong evidence", "Many people benefit from combining approaches (comprehensive care)", "Choice depends on severity, treatment history, preferences, and practical factors", "All three can be used together for optimal outcomes", "Treatment is individualized based on your unique needs and goals"]
  const faqs = [{question: "How do I know which treatment is right for me?", answer: "Discuss with a psychiatrist or therapist. They'll consider: severity of symptoms, what you've tried before, your preferences, practical factors (time, cost), and clinical recommendations. Often the best approach combines multiple treatments."}, {question: "Can I try therapy first before medication?", answer: "For mild-moderate depression/anxiety, yes—therapy is often effective alone. For moderate-severe symptoms or when functioning is significantly impaired, combining therapy with medication or TMS may be recommended from the start."}, {question: "What is comprehensive care?", answer: "Comprehensive care means combining multiple evidence-based treatments: TMS for brain stimulation, medication for chemical balance, therapy for skills and coping, all coordinated by one treatment team. Research shows combined approaches often work better than any single treatment."}, {question: "How long do different treatments take to work?", answer: "Therapy: 6-12 weeks for noticeable improvement. Medications: 4-8 weeks for full effect. TMS: 2-6 weeks of daily treatment. All require patience and consistency."}, {question: "What if one treatment doesn't work?", answer: "You have options. If therapy alone isn't enough, add medication or TMS. If medication doesn't work, try different medications, add therapy, or consider TMS. Treatment resistant doesn't mean untreatable—it means we need a different approach."}, {question: "Can I switch treatments if I don't like one?", answer: "Yes, but discuss with your provider first. Some transitions need to be gradual (tapering medication, completing TMS course). Your care team will help you safely try different approaches."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Understanding Your Treatment Options: A Comparison Guide" summary="Compare TMS, medication, and therapy: how each works, who they help, timelines, and how comprehensive care combines approaches." estimatedReadTime={15} lastReviewed="October 5, 2024" author="Tasel Health Medical Team" clinicalReviewer="Board-Certified Psychiatrist" tags={['Getting Started', 'Treatment Comparison', 'TMS', 'Medications', 'Therapy']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Treatment Approaches</h2><div className="space-y-4"><Card className="p-6 border-l-4 border-purple-500"><h3 className="text-xl font-bold text-gray-900 mb-2 flex items-center"><Brain className="h-6 w-6 text-purple-600 mr-2" />TMS (Transcranial Magnetic Stimulation)</h3><p className="text-gray-700 mb-2">Magnetic pulses stimulate underactive brain regions</p><p className="text-sm text-gray-600"><strong>Best for:</strong> Treatment-resistant depression, medication intolerance, prefer non-medication approach</p></Card><Card className="p-6 border-l-4 border-blue-500"><h3 className="text-xl font-bold text-gray-900 mb-2 flex items-center"><Pill className="h-6 w-6 text-blue-600 mr-2" />Medication Management</h3><p className="text-gray-700 mb-2">Psychiatric medications adjust brain chemistry</p><p className="text-sm text-gray-600"><strong>Best for:</strong> Moderate-severe symptoms, when therapy alone insufficient, long-term maintenance</p></Card><Card className="p-6 border-l-4 border-teal-500"><h3 className="text-xl font-bold text-gray-900 mb-2 flex items-center"><MessageSquare className="h-6 w-6 text-teal-600 mr-2" />Therapy & Counseling</h3><p className="text-gray-700 mb-2">Evidence-based talk therapy teaches coping skills</p><p className="text-sm text-gray-600"><strong>Best for:</strong> Mild-moderate symptoms, learning skills, addressing root causes, maintaining gains</p></Card><Card className="p-6 border-l-4 border-violet-500"><h3 className="text-xl font-bold text-gray-900 mb-2 flex items-center"><Sparkles className="h-6 w-6 text-violet-600 mr-2" />Spravato® & Ketamine</h3><p className="text-gray-700 mb-2">FDA-approved esketamine (Spravato®) and IV ketamine for rapid relief</p><p className="text-sm text-gray-600"><strong>Best for:</strong> TRD, rapid relief when other treatments haven&apos;t worked</p></Card></div></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Comprehensive Care Approach</h2><p className="mb-4">At Tasel Health, we specialize in comprehensive care—combining TMS, medication, and therapy for optimal outcomes. Research shows integrated treatment often works better than any single approach.</p><p className="mb-4">Learn more: <Link href="/services/comprehensive-care" className="text-purple-600 hover:underline">Comprehensive Mental Health Care</Link></p></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/tms-101-what-to-expect" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">TMS 101</h3><p className="text-sm text-gray-600">Brain stimulation</p></Card></Link><Link href="/knowledge-hub/antidepressants-explained" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Antidepressants</h3><p className="text-sm text-gray-600">Medications</p></Card></Link><Link href="/knowledge-hub/how-therapy-works" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">How Therapy Works</h3><p className="text-sm text-gray-600">Counseling</p></Card></Link><Link href="/knowledge-hub/ketamine-101-what-to-expect" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-violet-600">Ketamine 101</h3><p className="text-sm text-gray-600">Spravato® & Ketamine</p></Card></Link><Link href="/knowledge-hub/ketamine" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-violet-600">Spravato® & Ketamine Hub</h3><p className="text-sm text-gray-600">All Ketamine resources</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
