import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, TrendingUp, Target} from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Exposure Therapy: Build an Exposure Ladder for Anxiety & OCD', description: 'Learn to create exposure ladders: rank fears, practice gradual exposure, track habituation, and face anxiety systematically.', keywords: ['exposure therapy', 'exposure ladder', 'anxiety hierarchy', 'facing fears', 'OCD exposure']}

export default function ExposureLaddersPage() {
  const keyTakeaways = ["Exposure therapy is gold-standard treatment for anxiety disorders and OCD", "Exposure ladder ranks feared situations from least to most anxiety-provoking", "Start with easier exposures and gradually progress to harder ones", "Habituation (anxiety decrease) happens with repeated, prolonged exposure", "Therapist guidance helps make exposure safe and effective"]
  const faqs = [{question: "What is an exposure ladder?", answer: "A ranked list of feared situations from least to most anxiety-provoking (0-100 scale). You start at the bottom (lower anxiety items) and work your way up gradually as earlier exposures become easier."}, {question: "How do I create my exposure ladder?", answer: "With your therapist, list all situations you avoid due to anxiety. Rate each 0-100 for anxiety level. Arrange from lowest to highest. Identify specific, concrete steps for each level. Start with items rated around 30-40."}, {question: "How long should I stay in an exposure?", answer: "Stay until anxiety reduces by at least 50% (habituation). This might be 20-60 minutes depending on the situation. Leaving while anxiety is still high can reinforce fear. Your therapist will guide timing."}, {question: "What if my anxiety doesn't go down?", answer: "Sometimes the exposure is too difficult (start with easier step) or you're using safety behaviors (subtle avoidance that prevents habituation). Your therapist will help troubleshoot and adjust the plan."}, {question: "Can I do exposure therapy on my own?", answer: "While self-help is possible, working with a therapist is strongly recommended, especially for severe anxiety or OCD. Therapists ensure exposures are done correctly, provide support, and prevent common mistakes."}, {question: "Is exposure therapy safe?", answer: "Yes, when done properly. Exposure is uncomfortable but not harmful. You're in control—we never force you into situations. The goal is building confidence through gradual, supported challenge, not traumatization."}]
  const howToSchema = {"@context": "https://schema.org", "@type": "HowTo", "name": "How to Create and Use an Exposure Ladder", "step": [{"name": "List feared situations", "text": "Identify everything you avoid due to anxiety"}, {"name": "Rate anxiety level", "text": "Score each situation 0-100"}, {"name": "Arrange in order", "text": "Create ladder from easiest to hardest"}, {"name": "Start with manageable exposure", "text": "Begin with 30-40 rated items"}, {"name": "Practice until habituation", "text": "Stay in situation until anxiety drops 50%"}, {"name": "Progress upward", "text": "Move to next rung when current feels easier"}]}
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} /><ArticleLayout title="Exposure Ladders: Facing Anxiety Step-by-Step" summary="Create and use exposure ladders to gradually face fears: building your hierarchy, practicing exposures, and tracking progress." estimatedReadTime={12} lastReviewed="August 17, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Skills', 'Anxiety', 'Exposure Therapy', 'OCD', 'Phobias']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">How Exposure Works</h2><p className="mb-4">Exposure therapy is based on habituation—when you stay in an anxiety-provoking situation without escaping, your anxiety naturally decreases over time. Your brain learns the situation is safe.</p><p className="mb-4">Avoidance maintains anxiety. Exposure extinguishes it.</p></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Creating Your Exposure Ladder</h2><p className="mb-4"><strong>Example for Social Anxiety:</strong></p><ul className="list-disc pl-6 mb-4 space-y-1 text-sm"><li>10: Say hi to cashier</li><li>25: Make small talk with coworker</li><li>40: Ask question in small meeting</li><li>55: Attend social gathering for 30 minutes</li><li>70: Give presentation to small group</li><li>85: Attend party, talk to 5 people</li><li>100: Give speech to large audience</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Foa EB, McLean CP. (2016). "The efficacy of exposure therapy for anxiety-related disorders." Annual Review of Clinical Psychology 12:1-28.</li><li>2. Olatunji BO, et al. (2009). "Cognitive-behavioral therapy for anxiety disorders: A meta-analysis." Psychiatric Clinics of North America 32(3):527-544.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/5-minute-calm-breathing-grounding" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Breathing Techniques</h3><p className="text-sm text-gray-600">Anxiety management</p></Card></Link><Link href="/knowledge-hub/cbt-cognitive-behavioral-therapy" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">CBT Explained</h3><p className="text-sm text-gray-600">Cognitive therapy</p></Card></Link><Link href="/knowledge-hub/tms-for-ocd" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">TMS for OCD</h3><p className="text-sm text-gray-600">Brain stimulation</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
