import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Brain, Heart } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Mindfulness & Meditation: Basics for Mental Health', description: 'Learn mindfulness meditation for anxiety, depression, and stress: what it is, how to practice, benefits, and common obstacles.', keywords: ['mindfulness meditation', 'meditation for anxiety', 'mindfulness practice', 'meditation basics', 'mindfulness mental health']}

export default function MindfulnessPage() {
  const keyTakeaways = ["Mindfulness means paying attention to present moment without judgment", "Research shows benefits for anxiety, depression, stress, chronic pain", "Start with just 5-10 minutes daily; consistency matters more than duration", "Mind wandering is normal—gently return attention when it happens", "Many types of meditation; find what resonates with you"]
  const faqs = [{question: "What is mindfulness?", answer: "Mindfulness is intentionally paying attention to the present moment with openness and without judgment. It's about noticing your thoughts, feelings, and sensations as they are, rather than getting caught up in them or trying to change them."}, {question: "How do I start a meditation practice?", answer: "Start small: 5 minutes daily, same time each day. Sit comfortably, focus on your breath, notice when mind wanders (it will!), gently return attention to breath. Use apps (Headspace, Calm, Insight Timer) for guided meditations if helpful."}, {question: "What if I can't stop my thoughts?", answer: "You're not supposed to! The goal isn't stopping thoughts but changing your relationship with them. Notice thoughts arising, acknowledge them without judgment, and return focus to breath. Mind wandering is normal and expected."}, {question: "How long before mindfulness helps?", answer: "Some people feel calmer after just one session. Research-backed benefits (reduced anxiety, improved mood) typically emerge with 4-8 weeks of consistent daily practice. Like exercise, benefits build over time."}, {question: "Can mindfulness replace therapy or medication?", answer: "For mild symptoms, mindfulness may be enough. For moderate-severe mental health conditions, use mindfulness alongside professional treatment (therapy, medication). Mindfulness enhances treatment but doesn't replace it."}, {question: "What if meditation makes me more anxious?", answer: "This can happen, especially if you have trauma history or panic disorder. Try shorter sessions, walking meditation, or other forms of mindfulness (mindful eating, body scan). Discuss with a therapist—meditation isn't for everyone, and that's okay."}]
  const howToSchema = {"@context": "https://schema.org", "@type": "HowTo", "name": "Basic Mindfulness Meditation Practice", "step": [{"name": "Find quiet space", "text": "Sit comfortably in quiet location"}, {"name": "Set timer", "text": "Start with 5-10 minutes"}, {"name": "Focus on breath", "text": "Notice sensation of breathing"}, {"name": "Notice mind wandering", "text": "Acknowledge when thoughts arise"}, {"name": "Return to breath", "text": "Gently bring attention back without judgment"}, {"name": "Practice daily", "text": "Consistency builds the skill"}]}
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} /><ArticleLayout title="Mindfulness & Meditation: Basics for Mental Health" summary="Introduction to mindfulness meditation: what it is, how to practice, research-backed benefits, and getting started." estimatedReadTime={10} lastReviewed="April 27, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Skills', 'Mindfulness', 'Meditation', 'Self-Help', 'Anxiety', 'Stress']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">What Mindfulness Is (and Isn't)</h2><p className="mb-4"><strong>Mindfulness IS:</strong></p><ul className="list-disc pl-6 mb-4 space-y-1"><li>Paying attention to present moment</li><li>Noticing thoughts/feelings without getting caught in them</li><li>Accepting what is, as it is</li><li>A skill you can practice and improve</li></ul><p className="mb-4"><strong>Mindfulness ISN'T:</strong></p><ul className="list-disc pl-6 mb-4 space-y-1"><li>Stopping all thoughts (impossible!)</li><li>Always feeling calm or relaxed</li><li>Escaping problems or avoiding life</li><li>Religious (though used in some spiritual traditions)</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Research-Backed Benefits</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Reduces anxiety:</strong> Meta-analyses show significant anxiety reduction</li><li><strong>Improves depression:</strong> Mindfulness-based cognitive therapy prevents relapse</li><li><strong>Lowers stress:</strong> Reduces cortisol and stress reactivity</li><li><strong>Enhances focus:</strong> Improves attention and concentration</li><li><strong>Improves emotional regulation:</strong> Better ability to manage difficult emotions</li><li><strong>Physical health:</strong> Can lower blood pressure, improve immune function</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Khoury B, et al. (2013). "Mindfulness-based therapy: A comprehensive meta-analysis." Clinical Psychology Review 33(6):763-771.</li><li>2. Goyal M, et al. (2014). "Meditation programs for psychological stress and well-being: a systematic review and meta-analysis." JAMA Internal Medicine 174(3):357-368.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/5-minute-calm-breathing-grounding" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Breathing Techniques</h3><p className="text-sm text-gray-600">Quick mindfulness</p></Card></Link><Link href="/knowledge-hub/act-values-based-living" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">ACT Therapy</h3><p className="text-sm text-gray-600">Mindfulness in therapy</p></Card></Link><Link href="/knowledge-hub/stress-management-techniques" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Stress Management</h3><p className="text-sm text-gray-600">Comprehensive stress guide</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
