import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Users, Heart } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Couples & Family Therapy: Improving Relationships | Tasel Health', description: 'Learn what to expect from couples and family therapy: session format, communication skills, conflict resolution, and when relationship counseling helps.', keywords: ['couples therapy', 'family therapy', 'relationship counseling', 'marriage counseling Oklahoma City', 'family counseling']}

export default function CouplesFamilyTherapyPage() {
  const keyTakeaways = ["Couples/family therapy focuses on relationship dynamics and communication patterns", "Sessions involve all parties working together toward shared goals", "Evidence-based approaches improve communication, reduce conflict, strengthen bonds", "Both individual and relational factors are addressed", "Therapy is judgment-free—all perspectives are valued"]
  const faqs = [{question: "When should we consider couples therapy?", answer: "When communication has broken down, conflicts are frequent or unresolved, trust has been damaged, you're considering separation, or you want to strengthen your relationship. You don't have to wait until things are terrible—preventive work helps too."}, {question: "Do we both have to want therapy for it to work?", answer: "Ideally yes, but even if one partner is ambivalent, couples therapy can help. The therapist creates a safe space to explore concerns and resistance. However, both partners need to attend sessions for couples work."}, {question: "Will the therapist take sides?", answer: "No. Couples/family therapists remain neutral and help all parties understand each other's perspectives. The goal is improving the relationship system, not judging who's 'right' or 'wrong.'"}, {question: "What happens in couples therapy sessions?", answer: "Sessions focus on relationship patterns, communication skills, conflict resolution, and understanding each partner's needs. You'll practice new ways of interacting, both in session and at home. The therapist facilitates productive conversations."}, {question: "Can family therapy help with a difficult teenager?", answer: "Yes! Family therapy addresses family dynamics, parent-teen communication, boundary-setting, and adolescent behavioral/emotional issues. Teen participation is essential, and we work to engage them meaningfully."}, {question: "How long does couples/family therapy take?", answer: "Short-term focused work might be 8-12 sessions. Deeper or more complex relationship issues may take longer. We review progress regularly and discuss whether to continue."}, {question: "What if we decide to separate?", answer: "Couples therapy can help you make that decision thoughtfully, communicate it to children if relevant, and separate respectfully. Therapy doesn't always mean staying together—sometimes it means clarifying the healthiest path forward."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Couples & Family Therapy: What to Expect" summary="Guide to relationship counseling: how it differs from individual therapy, setting shared goals, improving communication, and when it helps." estimatedReadTime={11} lastReviewed="June 30, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Marriage & Family Therapist" tags={['Therapy', 'Couples Therapy', 'Family Therapy', 'Relationships']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">What Makes Relationship Therapy Different</h2><p className="mb-4">Unlike individual therapy, the "client" is the relationship system, not just one person. The therapist helps all parties communicate, understand each other, and work toward shared goals.</p></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Common Issues Addressed</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Communication breakdown:</strong> Learning to listen and express needs effectively</li><li><strong>Conflict patterns:</strong> Breaking destructive cycles</li><li><strong>Trust issues:</strong> Rebuilding after betrayal or addressing insecurity</li><li><strong>Intimacy concerns:</strong> Emotional and physical connection</li><li><strong>Life transitions:</strong> Adjusting to parenthood, job changes, empty nest</li><li><strong>Blended family challenges:</strong> Step-parenting and complex family dynamics</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Lebow JL, et al. (2012). "Research assessing couple and family therapies for depression." Journal of Marital and Family Therapy 38(1):48-81.</li><li>2. Gottman JM, Silver N. (2015). "The seven principles for making marriage work." Harmony Books.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/how-therapy-works" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">How Therapy Works</h3><p className="text-sm text-gray-600">Individual therapy</p></Card></Link><Link href="/knowledge-hub/dbt-skills-emotion-regulation" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Communication Skills</h3><p className="text-sm text-gray-600">DBT interpersonal effectiveness</p></Card></Link><Link href="/services/counseling" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Counseling Services</h3><p className="text-sm text-gray-600">Our therapy offerings</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
