import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Moon, Clock } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Sleep Better: CBT-I Guide for Insomnia | Evidence-Based Strategies', description: 'Improve sleep with Cognitive Behavioral Therapy for Insomnia (CBT-I): sleep hygiene, stimulus control, sleep restriction, and proven techniques.', keywords: ['CBT-I', 'how to sleep better', 'insomnia help', 'cognitive behavioral therapy insomnia', 'sleep hygiene']}

export default function SleepGuide() {
  const keyTakeaways = ["CBT-I is gold-standard insomnia treatment with lasting results", "Core techniques: sleep restriction, stimulus control, sleep hygiene", "Most people see improvement within 2-4 weeks of consistent practice", "Benefits continue after treatment—skills work long-term", "No medication side effects or dependence risks"]
  const faqs = [{question: "What is CBT-I?", answer: "Cognitive Behavioral Therapy for Insomnia is a structured program teaching behavioral and cognitive strategies to improve sleep without medication. It addresses the thoughts and behaviors keeping insomnia going."}, {question: "What is sleep restriction?", answer: "Temporarily limiting time in bed to match actual sleep time, then gradually expanding sleep window as sleep improves. It sounds counterintuitive but rebuilds sleep drive and consolidates sleep."}, {question: "What's stimulus control?", answer: "Retraining your brain that bed = sleep (not worry, TV, scrolling phone). Rules include: only go to bed when sleepy, get out of bed if awake 20+ minutes, use bed only for sleep and sex."}, {question: "How long does CBT-I take to work?", answer: "Most people notice improvement within 2-4 weeks of consistently applying techniques. Unlike medication (works immediately), CBT-I builds gradually but results last."}, {question: "Can I do CBT-I while taking sleep medication?", answer: "Yes, though the goal is often to taper medication as CBT-I skills improve sleep. Combining both initially, then reducing medication, is a common and effective approach."}, {question: "What if I work night shifts?", answer: "CBT-I can be adapted for shift workers. The principles (consistent sleep schedule, optimizing sleep environment, managing circadian rhythm) still apply but require modification for your schedule."}]
  const howToSchema = {"@context": "https://schema.org", "@type": "HowTo", "name": "How to Improve Sleep with CBT-I Techniques", "step": [{"name": "Set consistent sleep schedule", "text": "Go to bed and wake same time daily, even weekends"}, {"name": "Restrict time in bed", "text": "Only be in bed when actually sleeping"}, {"name": "Practice stimulus control", "text": "Use bed only for sleep; leave bed if awake 20+ min"}, {"name": "Improve sleep hygiene", "text": "Dark, cool room; avoid screens 1hr before bed"}, {"name": "Track progress", "text": "Keep sleep diary to monitor improvements"}]}
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} /><ArticleLayout title="Sleep Better: CBT-I Starter Guide" summary="Evidence-based strategies to improve sleep: sleep hygiene, stimulus control, sleep restriction, and when to seek professional help." estimatedReadTime={12} lastReviewed="October 20, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Skills', 'Sleep', 'Insomnia', 'CBT-I', 'Self-Help']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Core CBT-I Techniques</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Sleep Restriction:</strong> Match time in bed to actual sleep time</li><li><strong>Stimulus Control:</strong> Retrain bed = sleep association</li><li><strong>Sleep Hygiene:</strong> Optimize environment and behaviors</li><li><strong>Cognitive Therapy:</strong> Address anxious thoughts about sleep</li><li><strong>Relaxation:</strong> Progressive muscle relaxation, imagery</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Sleep Hygiene Basics</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li>Consistent sleep schedule (same bedtime/wake time daily)</li><li>Dark, cool, quiet bedroom (60-67°F ideal)</li><li>No screens 1 hour before bed</li><li>Avoid caffeine after 2pm</li><li>Limit alcohol (disrupts sleep quality)</li><li>Exercise regularly (but not within 3 hours of bedtime)</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Edinger JD, et al. (2021). "Behavioral and psychological treatments for chronic insomnia disorder in adults." J Clin Sleep Med 17(2):255-262.</li><li>2. Morin CM, et al. (2006). "Cognitive behavioral therapy, singly and combined with medication, for persistent insomnia." JAMA 296(17):2152-2160.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/sleep-medications-vs-cbt-i" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Sleep Meds vs CBT-I</h3><p className="text-sm text-gray-600">Compare approaches</p></Card></Link><Link href="/knowledge-hub/managing-anxiety-symptoms" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Anxiety Management</h3><p className="text-sm text-gray-600">Sleep and anxiety</p></Card></Link><Link href="/knowledge-hub/5-minute-calm-breathing-grounding" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Relaxation Techniques</h3><p className="text-sm text-gray-600">Bedtime calming</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
