import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Brain, Heart } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Understanding Depression: Symptoms, Causes & Treatment Options', description: 'Learn about major depressive disorder: symptoms, brain science, risk factors, and evidence-based treatment approaches.', keywords: ['understanding depression', 'major depressive disorder', 'depression symptoms', 'what is depression', 'depression treatment']}

export default function UnderstandingDepressionPage() {
  const keyTakeaways = ["Depression is a medical condition involving brain chemistry, not a character flaw or weakness", "Affects 21+ million American adults; highly treatable with multiple evidence-based options", "Symptoms include persistent sad mood, loss of interest, energy changes, sleep/appetite disruption", "Biological, psychological, and social factors all contribute to depression", "Treatment options include therapy, medication, TMS, and lifestyle interventions"]
  const faqs = [{question: "What causes depression?", answer: "Depression results from complex interaction of biological factors (genetics, brain chemistry), psychological factors (thinking patterns, trauma history), and social factors (stress, relationships, life events). It's not caused by one thing and isn't your fault."}, {question: "Is depression the same as sadness?", answer: "No. Sadness is a normal emotion that comes and goes. Depression is persistent (2+ weeks), affects functioning, includes multiple symptoms (not just sad mood), and doesn't improve with positive events. Depression is a medical condition requiring treatment."}, {question: "Can depression be cured?", answer: "Depression is treatable, and many people fully recover. However, it can be recurrent—about 50% of people who have one depressive episode will have another. Ongoing management (maintenance medication, therapy check-ins, lifestyle) helps prevent relapse."}, {question: "What if I'm depressed but don't feel sad?", answer: "Some people experience depression as numbness, emptiness, irritability, or loss of interest rather than sadness. Physical symptoms (fatigue, aches, sleep/appetite changes) may be more prominent. This is still depression and still treatable."}, {question: "How long does depression last?", answer: "Untreated, major depressive episodes average 6-8 months but can persist longer. With treatment, most people see significant improvement within 8-12 weeks. Early intervention shortens episodes and improves outcomes."}, {question: "Can depression come back after treatment?", answer: "Yes, depression can recur. Risk factors include stopping treatment prematurely, high life stress, previous multiple episodes. Maintenance treatment (staying on medication longer, periodic therapy check-ins) reduces recurrence risk."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Understanding Depression: Symptoms, Causes & Treatment" summary="Comprehensive guide to major depressive disorder: what it is, what causes it, how it's diagnosed, and evidence-based treatment options." estimatedReadTime={14} lastReviewed="September 18, 2024" author="Tasel Health Medical Team" clinicalReviewer="Board-Certified Psychiatrist" tags={['Depression', 'Mental Health', 'Education', 'Symptoms', 'Treatment Options']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Symptoms of Depression</h2><p className="mb-4"><strong>Core symptoms (need 5+ for 2+ weeks for diagnosis):</strong></p><ul className="list-disc pl-6 mb-4 space-y-1"><li>Depressed mood most of the day</li><li>Loss of interest or pleasure in activities</li><li>Significant weight/appetite changes</li><li>Insomnia or sleeping too much</li><li>Restlessness or slowed movements</li><li>Fatigue or low energy</li><li>Feelings of worthlessness or guilt</li><li>Difficulty concentrating or making decisions</li><li>Thoughts of death or suicide</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Treatment Options</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Psychotherapy:</strong> CBT, IPT, behavioral activation</li><li><strong>Medications:</strong> SSRIs, SNRIs, bupropion, others</li><li><strong>TMS:</strong> Brain stimulation for treatment-resistant depression</li><li><strong>Lifestyle:</strong> Exercise, sleep, social connection, nutrition</li><li><strong>Comprehensive care:</strong> Combining multiple approaches</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. American Psychiatric Association. (2013). Diagnostic and Statistical Manual of Mental Disorders (5th ed.).</li><li>2. National Institute of Mental Health. "Major Depression." <a href="https://www.nimh.nih.gov/health/statistics/major-depression" target="_blank" rel="noopener noreferrer" className="text-purple-600 hover:underline">NIMH Statistics</a></li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/tms-for-depression-evidence" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">TMS for Depression</h3><p className="text-sm text-gray-600">Brain stimulation</p></Card></Link><Link href="/knowledge-hub/antidepressants-explained" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Antidepressants</h3><p className="text-sm text-gray-600">Medication options</p></Card></Link><Link href="/knowledge-hub/behavioral-activation-depression" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Behavioral Activation</h3><p className="text-sm text-gray-600">Activity therapy</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
