import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, AlertTriangle, Heart } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'When to Seek Mental Health Help: Signs You Need Support', description: 'Recognize when mental health concerns need professional help: warning signs, what qualifies as needing treatment, and how to take the first step.', keywords: ['when to seek therapy', 'signs you need help', 'mental health warning signs', 'when to see psychiatrist', 'getting mental health help']}

export default function WhenToSeekHelpPage() {
  const keyTakeaways = ["You don't have to be in crisis to seek help—earlier intervention leads to better outcomes", "If symptoms interfere with work, relationships, or daily functioning, it's time to seek help", "Thoughts of suicide or self-harm require immediate professional attention", "Many people wait too long—seeking help is a sign of strength, not weakness", "Free consultation can help determine if treatment is appropriate for your situation"]
  const faqs = [{question: "Is my problem 'bad enough' for therapy?", answer: "If you're asking this question, the answer is probably yes. You don't need to be in crisis. If you're struggling, feeling stuck, or life feels harder than it should, therapy can help. Early intervention is easier and more effective than waiting until things are severe."}, {question: "When should I see a psychiatrist vs. a therapist?", answer: "Psychiatrists focus on medication management and diagnosis. Therapists provide counseling and skill-building. See a psychiatrist if you're considering medication, have severe symptoms, or need diagnostic evaluation. See a therapist for talk therapy. Many people benefit from both."}, {question: "What are warning signs I shouldn't ignore?", answer: "Changes in sleep or appetite, withdrawal from friends/activities, difficulty functioning at work/school, persistent sad or anxious mood (2+ weeks), loss of interest in things you used to enjoy, increased substance use, thoughts of suicide or self-harm."}, {question: "Do I need to wait until I'm suicidal to get help?", answer: "Absolutely not! Seek help much earlier—when you first notice persistent symptoms affecting your life. Waiting until crisis makes treatment harder and longer. Prevention and early intervention are far better than crisis management."}, {question: "How do I take the first step?", answer: "Start with a phone call to a mental health provider (like Tasel Health: 405-934-1681 for Oklahoma City or 210-202-2341 for San Antonio). We'll schedule a brief consultation to discuss your concerns and determine appropriate next steps. You can also start with your primary care doctor for a referral."}, {question: "What if I'm not sure what kind of help I need?", answer: "That's okay—that's what the initial consultation is for. We'll assess your situation and recommend appropriate treatment (therapy, medication, TMS, or combination). You don't need to diagnose yourself or know exactly what you need."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="When to Seek Mental Health Help: Signs You Need Support" summary="Recognize when mental health concerns need professional help, what qualifies as needing treatment, and how to take the first step." estimatedReadTime={10} lastReviewed="August 1, 2024" author="Tasel Health Medical Team" clinicalReviewer="Board-Certified Psychiatrist" tags={['Getting Started', 'Mental Health', 'Warning Signs', 'Seeking Help']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Signs It's Time to Seek Help</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li>Persistent sad, anxious, or empty mood (most days for 2+ weeks)</li><li>Loss of interest in activities you used to enjoy</li><li>Significant changes in sleep (insomnia or sleeping too much)</li><li>Energy changes (fatigue or restlessness)</li><li>Difficulty concentrating or making decisions</li><li>Changes in appetite or weight</li><li>Feeling worthless or excessively guilty</li><li>Physical symptoms without clear medical cause</li><li>Increased substance use to cope</li><li>Thoughts of death or suicide</li><li>Panic attacks or intense anxiety</li><li>Obsessive thoughts or compulsive behaviors</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Levels of Care</h2><div className="space-y-4"><Card className="p-6 bg-green-50 border-green-200"><h3 className="font-semibold text-gray-900 mb-2">Mild Symptoms</h3><p className="text-gray-700">Outpatient therapy, self-help strategies, lifestyle modifications</p></Card><Card className="p-6 bg-blue-50 border-blue-200"><h3 className="font-semibold text-gray-900 mb-2">Moderate Symptoms</h3><p className="text-gray-700">Outpatient therapy + medication, or TMS if medication-resistant</p></Card><Card className="p-6 bg-purple-50 border-purple-200"><h3 className="font-semibold text-gray-900 mb-2">Severe Symptoms</h3><p className="text-gray-700">Comprehensive care (multiple treatments), close monitoring, possible intensive outpatient programs</p></Card><Card className="p-6 bg-red-50 border-red-200"><h3 className="font-semibold text-gray-900 mb-2">Crisis/Emergency</h3><p className="text-gray-700">Immediate risk requires crisis services: 911, 988 Lifeline, emergency room</p></Card></div></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/getting-started-tasel-health" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Getting Started</h3><p className="text-sm text-gray-600">First visit guide</p></Card></Link><Link href="/knowledge-hub/understanding-depression" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Understanding Depression</h3><p className="text-sm text-gray-600">Depression info</p></Card></Link><Link href="/knowledge-hub/managing-anxiety-symptoms" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Managing Anxiety</h3><p className="text-sm text-gray-600">Anxiety guide</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
