import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Baby, Heart } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Perinatal Mental Health: Therapy During Pregnancy & Postpartum', description: 'Specialized counseling for pregnancy and postpartum: anxiety, depression, birth trauma, and adjustment challenges.', keywords: ['perinatal mental health', 'postpartum depression therapy', 'pregnancy anxiety', 'maternal mental health counseling']}

export default function PerinatalTherapyPage() {
  const keyTakeaways = ["Perinatal mental health issues affect 15-20% of new mothers", "Therapy is safe and effective during pregnancy and postpartum", "Specializes in pregnancy anxiety, postpartum depression, birth trauma", "Can help with adjustment, relationship changes, and parenting stress", "Many women benefit from combining therapy with medication or support groups"]
  const faqs = [{question: "When should I seek therapy during pregnancy?", answer: "If you're experiencing persistent sadness, anxiety, panic attacks, intrusive thoughts about harm, difficulty bonding with your baby, or overwhelming stress. Don't wait until you're in crisis—early support helps."}, {question: "Is therapy safe during pregnancy?", answer: "Yes! Therapy has no physical risks to baby and can significantly improve outcomes for both mother and child. Untreated perinatal mental health issues can affect pregnancy, birth, and bonding."}, {question: "What is postpartum depression?", answer: "Depression occurring after childbirth. Symptoms include persistent sadness, anxiety, difficulty bonding with baby, feeling overwhelmed, changes in sleep/appetite beyond normal newborn demands. It's common (10-15% of mothers) and treatable."}, {question: "How is perinatal therapy different from regular therapy?", answer: "Focuses on pregnancy-specific concerns: hormonal changes, body image, fear of childbirth, bonding, breastfeeding stress, role transitions, partner relationship shifts. Therapist understands normal vs. concerning perinatal symptoms."}, {question: "Can therapy help with birth trauma?", answer: "Yes. Traumatic birth experiences can lead to PTSD. Therapy helps process the trauma, manage symptoms, and address fears about future pregnancies or medical care."}, {question: "Do I need medication or is therapy enough?", answer: "Depends on severity. Mild-moderate perinatal anxiety/depression often responds well to therapy alone. Moderate-severe symptoms may benefit from combining therapy with pregnancy-safe medications. Discuss with your provider."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Perinatal Mental Health: Therapy for Pregnancy & Postpartum" summary="Specialized therapy for pregnancy and postpartum mental health: anxiety, depression, birth trauma, and adjustment support." estimatedReadTime={10} lastReviewed="June 6, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Therapy', 'Perinatal', 'Pregnancy', 'Postpartum', 'Maternal Mental Health']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Common Perinatal Mental Health Concerns</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Pregnancy anxiety:</strong> Fear of childbirth, health concerns, relationship worries</li><li><strong>Postpartum depression:</strong> Persistent sadness, difficulty bonding, overwhelming feelings</li><li><strong>Postpartum anxiety:</strong> Excessive worry about baby, intrusive thoughts, panic</li><li><strong>Birth trauma:</strong> PTSD from traumatic delivery experience</li><li><strong>Adjustment challenges:</strong> Role changes, identity shifts, relationship stress</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. O'Hara MW, McCabe JE. (2013). "Postpartum depression: current status and future directions." Annual Review of Clinical Psychology 9:379-407.</li><li>2. ACOG Committee Opinion No. 757. (2018). "Screening for perinatal depression." Obstetrics & Gynecology 132(5):e208-e212.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/medication-pregnancy-planning" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Medication & Pregnancy</h3><p className="text-sm text-gray-600">Medication decisions</p></Card></Link><Link href="/knowledge-hub/managing-anxiety-symptoms" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Managing Anxiety</h3><p className="text-sm text-gray-600">Anxiety strategies</p></Card></Link><Link href="/services/counseling" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Counseling Services</h3><p className="text-sm text-gray-600">Perinatal support</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
