import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Heart, Brain } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Managing Anxiety: Evidence-Based Strategies & Treatment Options', description: 'Comprehensive guide to anxiety management: symptoms, treatment approaches (therapy, medication, skills), and when to seek help.', keywords: ['managing anxiety', 'anxiety treatment', 'anxiety symptoms', 'anxiety relief', 'generalized anxiety disorder']}

export default function ManagingAnxietyPage() {
  const keyTakeaways = ["Anxiety is treatable with therapy, medication, or combination approaches", "CBT and exposure therapy have strongest evidence for anxiety disorders", "SSRIs/SNRIs are first-line medications; benzodiazepines not recommended long-term", "Skills like breathing, grounding, and cognitive restructuring provide immediate relief", "Lifestyle factors (sleep, exercise, caffeine, alcohol) significantly affect anxiety"]
  const faqs = [{question: "When does anxiety need professional treatment?", answer: "When it interferes with daily life (work, school, relationships), causes significant distress, includes panic attacks, or leads to avoidance of important activities. If you're wondering whether your anxiety is 'bad enough,' it probably warrants evaluation."}, {question: "What's the difference between normal anxiety and an anxiety disorder?", answer: "Everyone feels anxious sometimes. An anxiety disorder means anxiety is persistent, excessive, disproportionate to the situation, and interferes with functioning. Anxiety disorders are diagnosable conditions requiring treatment."}, {question: "Will I need medication for anxiety?", answer: "Not everyone does. Mild-moderate anxiety often responds well to therapy alone. Moderate-severe anxiety may benefit from combining medication (usually SSRIs/SNRIs) with therapy. Your provider will recommend based on your severity and preferences."}, {question: "How do I know if I'm having a panic attack?", answer: "Sudden intense fear with physical symptoms: racing heart, sweating, shaking, shortness of breath, chest pain, dizziness, fear of dying. Peaks within minutes. Panic attacks are frightening but not dangerous. If uncertain whether it's panic or medical emergency, seek medical evaluation."}, {question: "Can anxiety cause physical symptoms?", answer: "Yes! Anxiety commonly causes: rapid heartbeat, chest tightness, shortness of breath, stomach upset, muscle tension, headaches, dizziness, tingling. These are real physical sensations caused by nervous system activation, not 'all in your head.'"}, {question: "Should I avoid situations that make me anxious?", answer: "Short-term avoidance provides relief but long-term avoidance maintains and worsens anxiety. Gradual exposure (facing fears in controlled way) is how anxiety improves. Therapy helps you face anxiety-provoking situations safely."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Managing Anxiety: Comprehensive Guide" summary="Evidence-based strategies for managing anxiety: treatment options, self-help tools, and when to seek professional help." estimatedReadTime={13} lastReviewed="December 3, 2024" author="Tasel Health Medical Team" clinicalReviewer="Board-Certified Psychiatrist" tags={['Anxiety', 'Mental Health', 'Treatment Options', 'Self-Help']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Treatment Options for Anxiety</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Therapy (CBT, exposure):</strong> Most effective long-term treatment</li><li><strong>Medications (SSRIs, SNRIs):</strong> First-line medications for anxiety disorders</li><li><strong>Skills training (breathing, mindfulness):</strong> Practical tools for managing symptoms</li><li><strong>Lifestyle modifications:</strong> Exercise, sleep, reducing caffeine/alcohol</li><li><strong>Combination approach:</strong> Often most effective, especially for moderate-severe anxiety</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Quick Anxiety Relief Techniques</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Box breathing:</strong> 4-4-4-4 pattern calms nervous system</li><li><strong>5-4-3-2-1 grounding:</strong> Brings you to present moment</li><li><strong>Progressive muscle relaxation:</strong> Tense and release muscle groups</li><li><strong>Cold water:</strong> Splash face to activate dive reflex</li></ul><p className="mb-4">Learn more: <Link href="/knowledge-hub/5-minute-calm-breathing-grounding" className="text-purple-600 hover:underline">5-Minute Calm: Breathing Techniques</Link></p></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Bandelow B, et al. (2015). "Efficacy of treatments for anxiety disorders: a meta-analysis." International Clinical Psychopharmacology 30(4):183-192.</li><li>2. Hofmann SG, Smits JAJ. (2008). "Cognitive-behavioral therapy for adult anxiety disorders." J Clin Psychiatry 69(4):621-632.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/exposure-ladders-anxiety" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Exposure Ladders</h3><p className="text-sm text-gray-600">Facing fears</p></Card></Link><Link href="/knowledge-hub/antidepressants-explained" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Anxiety Medications</h3><p className="text-sm text-gray-600">SSRIs for anxiety</p></Card></Link><Link href="/knowledge-hub/5-minute-calm-breathing-grounding" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Quick Relief</h3><p className="text-sm text-gray-600">Breathing techniques</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
