import { Metadata} from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Stress Management: Evidence-Based Techniques for Daily Life', description: 'Learn practical stress management strategies: time management, boundaries, relaxation, social support, and when stress needs professional help.', keywords: ['stress management', 'stress relief techniques', 'managing stress', 'stress reduction', 'coping with stress']}

export default function StressManagementPage() {
  const keyTakeaways = ["Chronic stress affects mental and physical health—managing it is essential", "Effective stress management includes problem-solving and emotion-focused coping", "Regular practice of stress reduction techniques builds resilience", "Social support, exercise, and sleep are foundational for stress resilience", "When stress becomes overwhelming or causes symptoms, professional help recommended"]
  const faqs = [{question: "What's the difference between stress and anxiety?", answer: "Stress is a response to external demands or pressures. Anxiety is worry about potential threats, often without clear external trigger. Chronic stress can lead to anxiety disorders. Both benefit from similar management strategies."}, {question: "When does stress require professional help?", answer: "When stress causes persistent physical symptoms (headaches, stomach issues, sleep problems), leads to substance use, interferes with work/relationships, or triggers depression/anxiety. If stress feels unmanageable, seek evaluation."}, {question: "Can stress cause depression?", answer: "Chronic stress is a major risk factor for depression. Prolonged stress can alter brain chemistry and structure, making depression more likely. Managing stress effectively helps prevent depression."}, {question: "What's the fastest way to reduce stress?", answer: "Quick techniques: deep breathing (activates relaxation response), brief walk (physical outlet), talking to supportive person, progressive muscle relaxation. These provide immediate relief. Long-term stress reduction requires lifestyle changes."}, {question: "How does exercise help stress?", answer: "Exercise reduces stress hormones (cortisol, adrenaline), releases endorphins (natural mood boosters), improves sleep, and provides distraction from worries. Even 20-30 minutes of moderate exercise helps."}, {question: "Can I eliminate stress from my life?", answer: "No, and you wouldn't want to—some stress is motivating and normal. The goal is managing stress effectively so it doesn't become chronic or overwhelming. Building coping skills and resilience is key."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><ArticleLayout title="Stress Management: Practical Techniques" summary="Evidence-based stress management strategies you can use daily: coping skills, lifestyle factors, and when to seek help." estimatedReadTime={10} lastReviewed="April 19, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Skills', 'Stress Management', 'Coping', 'Self-Help', 'Prevention']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Effective Stress Management Strategies</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>Problem-solving:</strong> Address stressors you can control</li><li><strong>Time management:</strong> Prioritize, delegate, say no to non-essentials</li><li><strong>Boundaries:</strong> Protect your time and energy</li><li><strong>Social support:</strong> Connect with supportive people</li><li><strong>Exercise:</strong> Regular physical activity reduces stress</li><li><strong>Sleep:</strong> Adequate rest is foundational</li><li><strong>Relaxation practices:</strong> Breathing, meditation, yoga</li><li><strong>Limit stressors:</strong> Reduce caffeine, news consumption, toxic relationships where possible</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. American Psychological Association. (2019). "Stress in America 2019." <a href="https://www.apa.org/news/press/releases/stress" target="_blank" rel="noopener noreferrer" className="text-purple-600 hover:underline">APA Stress Survey</a></li><li>2. Carver CS, et al. (1989). "Assessing coping strategies: a theoretically based approach." J Pers Soc Psychol 56(2):267-283.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/5-minute-calm-breathing-grounding" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Breathing Techniques</h3><p className="text-sm text-gray-600">Quick stress relief</p></Card></Link><Link href="/knowledge-hub/sleep-better-cbt-i-guide" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Sleep Better</h3><p className="text-sm text-gray-600">Sleep and stress</p></Card></Link><Link href="/knowledge-hub/managing-anxiety-symptoms" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Managing Anxiety</h3><p className="text-sm text-gray-600">Anxiety strategies</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
