import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Activity, TrendingUp } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: 'Behavioral Activation for Depression: Activity Scheduling Guide', description: 'Break the depression cycle with behavioral activation: plan activities, track mood, build momentum, and reconnect with what matters.', keywords: ['behavioral activation', 'depression activity scheduling', 'overcoming depression', 'mood activity relationship']}

export default function BehavioralActivationPage() {
  const keyTakeaways = ["Depression causes withdrawal from activities, which worsens depression—a vicious cycle", "Behavioral activation breaks this cycle by scheduling meaningful activities", "Start small—even brief activities can improve mood", "Track mood and activity connection to see what helps", "Core component of CBT with strong evidence base"]
  const faqs = [{question: "What is behavioral activation?", answer: "A core CBT technique where you schedule and engage in meaningful activities, even when you don't feel like it. The idea: action precedes motivation in depression. By doing things, mood improves, which then increases motivation."}, {question: "How do I start if I have no energy?", answer: "Start very small. One 10-minute activity (walk around block, call a friend, organize one drawer). Success builds on success. You don't need energy to start—energy comes from doing."}, {question: "What activities should I choose?", answer: "Mix of: enjoyable activities (what used to bring pleasure), important activities (values-aligned), social activities (connection with others), and physical activities (movement helps mood). Your therapist helps identify meaningful options."}, {question: "What if activities don't improve my mood?", answer: "Some activities have delayed mood payoff. Track over time—you might not feel better immediately after but notice patterns over days/weeks. Also, some activities prevent mood from worsening (valuable even without immediate lift)."}, {question: "Is behavioral activation as effective as medication?", answer: "For mild-moderate depression, yes—research shows behavioral activation can be as effective as antidepressants. For severe depression, combining behavioral activation with medication often works best."}, {question: "How do I track the mood-activity connection?", answer: "Use a simple log: date/time, activity, mood rating before (1-10), mood rating after (1-10), plus brief notes. Over time, patterns emerge showing which activities boost your mood most."}]
  const howToSchema = {"@context": "https://schema.org", "@type": "HowTo", "name": "How to Use Behavioral Activation for Depression", "step": [{"name": "Identify meaningful activities", "text": "List activities from your past or values"}, {"name": "Schedule specific times", "text": "Put activities in calendar, start small"}, {"name": "Do activity regardless of mood", "text": "Follow schedule even when unmotivated"}, {"name": "Track mood before and after", "text": "Rate mood 1-10 to see impact"}, {"name": "Gradually increase activities", "text": "Build on successes, expand schedule"}]}
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} /><ArticleLayout title="Behavioral Activation: Moving Through Depression" summary="Learn behavioral activation: how to break the cycle of depression by scheduling activities, tracking mood, and building momentum." estimatedReadTime={11} lastReviewed="September 10, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Skills', 'Depression', 'Behavioral Activation', 'Activity Scheduling']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">The Depression Cycle</h2><p className="mb-4">Depression → Withdrawal from activities → More depression → More withdrawal. Behavioral activation breaks this cycle by reversing the pattern: Schedule activities → Do them (even when unmotivated) → Mood improves → More motivation to do more.</p></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">How to Practice Behavioral Activation</h2><ol className="list-decimal pl-6 mb-4 space-y-3"><li><strong>List potential activities:</strong> Things you used to enjoy, values-aligned actions, social connections</li><li><strong>Start small:</strong> Choose 1-2 brief activities for this week</li><li><strong>Schedule specifically:</strong> Write in calendar: "Tuesday 2pm, 20-min walk"</li><li><strong>Do it regardless of mood:</strong> Follow schedule even if unmotivated</li><li><strong>Track mood impact:</strong> Rate mood before and after</li><li><strong>Review and adjust:</strong> What helped? Do more of that</li><li><strong>Gradually expand:</strong> Add more activities as energy builds</li></ol></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Dimidjian S, et al. (2006). "Randomized trial of behavioral activation, cognitive therapy, and antidepressant medication in the acute treatment of adults with major depression." J Consult Clin Psychol 74(4):658-670.</li><li>2. Lejuez CW, et al. (2011). "A brief behavioral activation treatment for depression." Behavior Modification 35(2):164-186.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/cbt-cognitive-behavioral-therapy" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">CBT Explained</h3><p className="text-sm text-gray-600">Cognitive therapy</p></Card></Link><Link href="/knowledge-hub/antidepressants-explained" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Antidepressants</h3><p className="text-sm text-gray-600">Medication options</p></Card></Link><Link href="/knowledge-hub/understanding-depression" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Understanding Depression</h3><p className="text-sm text-gray-600">Condition overview</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
