import { Metadata } from 'next'
import { ArticleLayout } from '@/components/knowledge/article-layout'
import { Card } from '@/components/ui/card'
import { CheckCircle, Wind, Smartphone } from 'lucide-react'
import { StillHaveQuestions } from '@/components/sections/still-have-questions'
import Link from 'next/link'

export const metadata: Metadata = {title: '5-Minute Calm: Breathing & Grounding Techniques for Anxiety', description: 'Learn quick anxiety relief techniques: box breathing, 5-4-3-2-1 grounding, and other evidence-based tools to calm your nervous system.', keywords: ['breathing techniques anxiety', 'grounding techniques', 'box breathing', '5-4-3-2-1 technique', 'calm anxiety fast']}

export default function BreathingGroundingPage() {
  const keyTakeaways = ["Breathing techniques calm your nervous system in minutes", "Grounding brings you back to present moment when anxious or dissociating", "These are evidence-based tools used in DBT, CBT, and trauma therapy", "Practice when calm so skills are available when you need them", "No equipment needed—use these tools anywhere, anytime"]
  const faqs = [{question: "How does breathing help anxiety?", answer: "Deep, slow breathing activates your parasympathetic nervous system (rest and digest response), counteracting the fight-or-flight response. It slows heart rate, lowers blood pressure, and signals your brain that you're safe."}, {question: "What is box breathing?", answer: "Box breathing (4-4-4-4): Inhale for 4 counts, hold for 4, exhale for 4, hold for 4. Repeat 4-5 times. It's called 'box' because each phase is equal length, like the sides of a square. Used by Navy SEALs for stress management."}, {question: "What's the 5-4-3-2-1 grounding technique?", answer: "Name 5 things you see, 4 things you can touch, 3 things you hear, 2 things you smell, 1 thing you taste. This brings you into the present moment and out of anxious thoughts or dissociation."}, {question: "When should I use these techniques?", answer: "Use when you feel anxiety building, during panic attacks, when overwhelmed, before stressful situations, or anytime you need to calm down. Also practice daily when calm to build the skill."}, {question: "Why should I practice when I'm not anxious?", answer: "Like any skill, breathing and grounding work better when you've practiced them. Practicing when calm builds the neural pathways so the techniques are automatic and effective when you really need them."}, {question: "Can breathing exercises replace medication or therapy?", answer: "No—these are coping tools, not treatments. They're excellent for managing symptoms in the moment, but professional treatment addresses underlying anxiety disorders. Use breathing techniques alongside therapy and/or medication."}, {question: "What if focusing on breathing makes anxiety worse?", answer: "Some people with trauma or panic disorder feel more anxious when focusing on breath. If this happens, try grounding techniques (5-4-3-2-1) or distraction instead. Tell your therapist—they can suggest alternatives."}]
  const faqSchema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(faq => ({"@type": "Question", "name": faq.question, "acceptedAnswer": {"@type": "Answer", "text": faq.answer}}))}
  const howToSchema = {"@context": "https://schema.org", "@type": "HowTo", "name": "Box Breathing Technique for Anxiety", "step": [{"name": "Inhale", "text": "Breathe in slowly through nose for 4 seconds"}, {"name": "Hold", "text": "Hold your breath for 4 seconds"}, {"name": "Exhale", "text": "Breathe out slowly through mouth for 4 seconds"}, {"name": "Hold", "text": "Hold breath out for 4 seconds"}, {"name": "Repeat", "text": "Continue for 4-5 cycles"}]}

  return (<><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} /><ArticleLayout title="5-Minute Calm: Breathing & Grounding Techniques" summary="Quick, proven techniques to calm anxiety and stress: box breathing, 5-4-3-2-1 grounding, and other tools you can use anywhere." estimatedReadTime={9} lastReviewed="November 10, 2024" author="Tasel Health Medical Team" clinicalReviewer="Licensed Clinical Psychologist" tags={['Skills', 'Breathing', 'Grounding', 'Anxiety', 'Self-Help']}><Card className="p-6 bg-teal-50 border-teal-200 mb-8"><h2 className="text-2xl font-bold text-gray-900 mb-4">Key Takeaways</h2><ul className="space-y-2">{keyTakeaways.map((t, i) => (<li key={i} className="flex items-start space-x-3"><CheckCircle className="h-5 w-5 text-teal-600 flex-shrink-0 mt-0.5" /><span className="text-gray-700">{t}</span></li>))}</ul></Card>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Box Breathing (4-4-4-4)</h2><ol className="list-decimal pl-6 mb-4 space-y-2"><li><strong>Inhale</strong> through nose for 4 seconds</li><li><strong>Hold</strong> breath for 4 seconds</li><li><strong>Exhale</strong> through mouth for 4 seconds</li><li><strong>Hold</strong> empty for 4 seconds</li><li><strong>Repeat</strong> 4-5 cycles</li></ol></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">5-4-3-2-1 Grounding</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>5 things you SEE</strong> around you</li><li><strong>4 things you can TOUCH</strong></li><li><strong>3 things you HEAR</strong></li><li><strong>2 things you SMELL</strong></li><li><strong>1 thing you TASTE</strong></li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-4">Other Quick Techniques</h2><ul className="list-disc pl-6 mb-4 space-y-2"><li><strong>4-7-8 Breathing:</strong> Inhale 4, hold 7, exhale 8</li><li><strong>Diaphragmatic Breathing:</strong> Belly breathing to engage relaxation response</li><li><strong>Progressive Muscle Relaxation:</strong> Tense and release muscle groups</li><li><strong>Cold Water:</strong> Splash face or hold ice—activates dive reflex</li></ul></section>

        <section className="mb-8"><h2 className="text-3xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="border-l-4 border-purple-500 pl-4 py-2"><h3 className="text-lg font-semibold text-gray-900 mb-2">{faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></section>

        <section className="mb-8 text-sm text-gray-600"><h2 className="text-2xl font-bold text-gray-900 mb-4">References</h2><ul className="space-y-2"><li>1. Gerritsen RJS, Band GPH. (2018). "Breath of life: The respiratory vagal stimulation model of contemplative activity." Front Hum Neurosci 12:397.</li><li>2. Napadow V, et al. (2008). "The imagined hand: A pilot fMRI study of grounding." NeuroImage 42(2):710-722.</li></ul></section>

        <section><h2 className="text-3xl font-bold text-gray-900 mb-6">Related Articles</h2><div className="grid md:grid-cols-3 gap-6"><Link href="/knowledge-hub/dbt-skills-emotion-regulation" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">DBT Distress Tolerance</h3><p className="text-sm text-gray-600">More crisis skills</p></Card></Link><Link href="/knowledge-hub/managing-anxiety-symptoms" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Managing Anxiety</h3><p className="text-sm text-gray-600">Comprehensive anxiety guide</p></Card></Link><Link href="/knowledge-hub/trauma-therapy-approaches" className="group"><Card className="p-6 hover:shadow-lg transition-shadow"><h3 className="font-bold text-gray-900 mb-2 group-hover:text-purple-600">Trauma Therapy</h3><p className="text-sm text-gray-600">PTSD treatment</p></Card></Link></div></section>
      </ArticleLayout><StillHaveQuestions /></>)
}
